### ISSUE TITLE
Remove CSV support from Pretty Diff

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/beautifier-prettydiff#18]
Go to http://prettydiff.com/

```
value1,value2,value3,value4,value5,value6
```

![image](https://user-images.githubusercontent.com/1885333/36654063-60621886-1a90-11e8-8ca5-f8403317ccdf.png)

And the tests:

```
Summary of all failing tests
 FAIL  test/languages/csv.spec.ts
  ● should successfully beautify CSV text

    TypeError: value.split is not a function

      at Diff.Object.<anonymous>.lineDiff.tokenize (node_modules/diff/src/diff/line.js:7:32)
      at Diff.diff (node_modules/diff/src/diff/base.js:28:39)
      at diffLines (node_modules/diff/src/diff/line.js:31:71)
      at structuredPatch (node_modules/diff/src/patch/create.js:11:16)
      at Object.createTwoFilesPatch (node_modules/diff/src/patch/create.js:101:16)
      at InlineFlagManager.get rawPatch [as rawPatch] (node_modules/unibeautify/src/InlineFlagManager.ts:56:7)
      at InlineFlagManager.get patch [as patch] (node_modules/unibeautify/src/InlineFlagManager.ts:39:13)
      at InlineFlagManager.get text [as text] (node_modules/unibeautify/src/InlineFlagManager.ts:17:13)
      at beautifier.beautify.then.newText (node_modules/unibeautify/src/beautifier.ts:371:29)

```

**Comment by szeck87** [comment]
Looks like this just removed the test.  We should also remove, or comment out at least, https://github.com/Unibeautify/beautifier-prettydiff/blob/master/src/index.ts#L16 and https://github.com/Unibeautify/beautifier-prettydiff/blob/master/src/index.ts#L43-L45
